/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/buscar' | '/categoria/$slug' | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/buscar' | '/categoria/$slug' | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/categoria/$slug'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscarRoute: typeof BuscarRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscarRoute: BuscarRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
